nodeLinker: hoisted
allowBuilds:
  unrs-resolver: true
patchedDependencies:
  expo-audio: patches/expo-audio.patch
  expo-network: patches/expo-network.patch
  react-native-image-colors: patches/react-native-image-colors.patch
